// ============================================
// Shared Game State & Configuration
// All modules import from here
// ============================================

/* ---- Config ---- */
export const STANDARD_VALUES = [
  .01, 1, 5, 10, 25, 50, 75, 100, 200, 300, 400, 500, 750,
  1000, 5000, 10000, 25000, 50000, 75000, 100000, 200000, 300000, 400000, 500000, 750000, 1000000
];
export const MIN_CASE_COUNT = 4;
export const MAX_CASE_COUNT = 26;

/* ---- State ---- */
export const game = {
  caseCount: 26,
  nextCaseCount: 26,
  schedule: [],
  amounts: [],
  caseAssignment: [],
  yourCase: null,
  openedCases: new Set(),
  state: 'setup',
  roundIndex: 0,
  openedInRound: 0,
  roundEliminatedValues: [],
  lastOffer: null,
  offerHistory: [],
  counterOfferUsed: false,
  pendingCounterOffer: null,
  pendingCounterAccepted: null,
  postDealMode: false,
  dealTakenAmount: null,
  hypotheticalOffers: [],
  revealMode: 'real',
  editMode: false,
  manualOpenMode: false,
  nightVisionMode: false,
  showCurrencyBoard: false,
  showCurrencyBriefcase: false,
  hideOpenedCases: false,
  gameLogEnabled: true,
  sfxEnabled: true,
  sfxVolumePercent: 130, // 100% = normal; defaulted louder per request
  boardRowEls: {},
  gameLog: [],
};

/* ---- DOM refs ---- */
const $ = id => document.getElementById(id);

export const dom = {
  statusLine: $('statusLine'),
  yourCaseHolder: $('yourCaseHolder'),
  caseGrid: $('caseGrid'),
  boardColLow: $('boardColLow'),
  boardColHigh: $('boardColHigh'),
  editToggle: $('editToggle'),
  saveValuesBtn: $('saveValuesBtn'),
  shuffleBtn: $('shuffleBtn'),
  resetValuesBtn: $('resetValuesBtn'),
  spotlightBackdrop: $('spotlightBackdrop'),
  dangerFlash: $('dangerFlash'),
  centerStage: $('centerStage'),
  centerCase: $('centerCase'),
  centerStageLabel: $('centerStageLabel'),
  offersPanel: $('offersPanel'),
  bankerOfferDisplay: $('bankerOfferDisplay'),
  offersList: $('offersList'),
  settingsGear: $('settingsGear'),
  settingsPanel: $('settingsPanel'),
  manualModeToggle: $('manualModeToggle'),
  nightVisionToggle: $('nightVisionToggle'),
  currencyBoardToggle: $('currencyBoardToggle'),
  currencyBriefcaseToggle: $('currencyBriefcaseToggle'),
  hideOpenedCasesToggle: $('hideOpenedCasesToggle'),
  gameLogEnabledToggle: $('gameLogEnabledToggle'),
  soundToggle: $('soundToggle'),
  sfxVolumeInput: $('sfxVolumeInput'),
  suggestBtn: $('suggestBtn'),
  suggestPanel: $('suggestPanel'),
  suggestBody: $('suggestBody'),
  suggestRegenBtn: $('suggestRegenBtn'),
  closeSuggestBtn: $('closeSuggestBtn'),
  bgPickerBtn: $('bgPickerBtn'),
  bgPickerPanel: $('bgPickerPanel'),
  bgPickerGrid: $('bgPickerGrid'),
  boardBgPickerGrid: $('boardBgPickerGrid'),
  closeBgPickerBtn: $('closeBgPickerBtn'),
  caseCountInput: $('caseCountInput'),
  applyCaseCountBtn: $('applyCaseCountBtn'),
  saveSettingsBtn: $('saveSettingsBtn'),
  closeSettingsBtn: $('closeSettingsBtn'),
  pbSelectBtn: $('pbSelectBtn'),
  pbSelectPanel: $('pbSelectPanel'),
  pbSaveName: $('pbSaveName'),
  pbSaveConfirmBtn: $('pbSaveConfirmBtn'),
  pbList: $('pbList'),
  closePbSelectBtn: $('closePbSelectBtn'),
  boardSaveBtn: $('boardSaveBtn'),
  gameLogPanel: $('gameLogPanel'),
  gameLogHeader: $('gameLogHeader'),
  gameLogList: $('gameLogList'),
  customBankOfferWrap: $('customBankOfferWrap'),
  customBankOfferBtn: $('customBankOfferBtn'),
  customBankOfferInput: $('customBankOfferInput'),
  manualSlider: $('manualSlider'),
  sliderTrack: $('sliderTrack'),
  sliderFill: $('sliderFill'),
  sliderHandle: $('sliderHandle'),
  offerBackdrop: $('offerBackdrop'),
  offerStatus: $('offerStatus'),
  offerContent: $('offerContent'),
  offerLabel: $('offerLabel'),
  revealOfferBtn: $('revealOfferBtn'),
  continuePlayoutBtn: $('continuePlayoutBtn'),
  acknowledgeDealBtn: $('acknowledgeDealBtn'),
  instantRevealBtn: $('instantRevealBtn'),
  postDealActions: $('postDealActions'),
  offerButtonsRow: $('offerButtonsRow'),
  dealBtn: $('dealBtn'),
  noDealBtn: $('noDealBtn'),
  counterLinkBtn: $('counterLinkBtn'),
  counterPanel: $('counterPanel'),
  counterInput: $('counterInput'),
  counterStatus: $('counterStatus'),
  submitCounterBtn: $('submitCounterBtn'),
  cancelCounterBtn: $('cancelCounterBtn'),
  offerModalEl: $('bankerCallCard'),
  phoneIconEl: document.querySelector('.phone-icon'),
  finalBackdrop: $('finalBackdrop'),
  finalSub: $('finalSub'),
  finalCases: $('finalCases'),
  endBackdrop: $('endBackdrop'),
  endTitle: $('endTitle'),
  endSub: $('endSub'),
  endResults: $('endResults'),
  badDecisionNote: $('badDecisionNote'),
  playAgainBtn: $('playAgainBtn'),
  manualBackBtn: $('manualBackBtn'),
  manualContinueBtn: $('manualContinueBtn'),
};
